### ISSUE TITLE
gsinfo not installing

### ISSUE THREAD

**Issue by baid12345** [Shigbeard/shigbeard-cogs#2]
I've been looking for a cog for a while like this and I wish to use it. However when I attempt to add it all I get is "Error in command 'cog install'. Check your console or logs for details.". I tried adding the python valve thing and beatifulsoap4 into my cogs file (not sure if this is correct) and nothing still. Some help would be greatly appreciated as I wish to use this cog.

Many thanks,

**Comment by Shigbeard** [comment]
Can you show me the error in your console or logs? Thank you.

**Comment by baid12345** [comment]
http://prntscr.com/grxtfh

**Comment by Shigbeard** [comment]
See if that fixes your issue. You will need to uninstall and remove the repo from your bot before reinstalling it again. If that still doesn't work, you can manually copy across the script into the cogs folder and load it with `[p]load gsinfo`
